### ISSUE TITLE
How to modify CPU training instead of GPU in DLmodel_python_code.py file？

### ISSUE THREAD

**Issue by fc-smile2** [WSLCL/DeepLearning-CoordinatedBeamforming#1]
In the case of data set applications, ”Deep Learning Coordinated Beamforming for Highly-Mobile Millimeter Wave Systems” is trained with GPU in ‘DL model_python_code.py file', but my computer does not have GPU, so how should I modify this file to use CPU training?

**Comment by yaling1230** [comment]
并不需要更改什么，只需要将"os.environ["THEANO_FLAGS"]  = "device=gpu%d"%(1)"这行注释掉就可以使用了，但CPU训练较慢，推荐使用GPU。
